spring.application.name=rentacar

management.endpoints.web.exposure.include=prometheus,health,info

management.endpoints.web.base-path=/actuator

management.metrics.tags.application=${spring.application.name}
