{
 "title": "Microservicio Rentacar - Control de Mandos",
 "tags": [
  "springboot",
  "rentacar"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Uso de CPU (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "process_cpu_usage{job=\"spring-boot-app\"} * 100",
     "legendFormat": "JVM (App Rentacar)"
    },
    {
     "expr": "system_cpu_usage{job=\"spring-boot-app\"} * 100",
     "legendFormat": "Sistema Operativo (Host)"
    }
   ]
  },
  {
   "title": "Uso de Memoria Heap (JVM)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{job=\"spring-boot-app\", area=\"heap\"})",
     "legendFormat": "Memoria Usada"
    },
    {
     "expr": "sum(jvm_memory_committed_bytes{job=\"spring-boot-app\", area=\"heap\"})",
     "legendFormat": "Memoria Reservada"
    }
   ]
  },
  {
   "title": "Rendimiento y Llamadas por Endpoint (RPS)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_count{job=\"spring-boot-app\"}[1m])",
     "legendFormat": "{{uri}} [{{status}}]"
    }
   ]
  },
  {
   "title": "Tiempos de Respuesta Promedio (Latencia)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_sum{job=\"spring-boot-app\"}[1m]) / rate(http_server_requests_seconds_count{job=\"spring-boot-app\"}[1m]) * 1000",
     "legendFormat": "{{uri}} (ms)"
    }
   ]
  }
 ]
}